//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmRad.ContentProjects.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_DATA
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string TEXT { get; set; }
    }
}
